#!/bin/bash
pip3 install -r requirements.txt
python3 manage.py makemigrations
python3 manage.py collectstatic
python3 manage.py migrate
sudo systemctl restart gunicorn.socket
sudo systemctl restart gunicorn.service
sudo systemctl restart nginx.service

