# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20190823_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.CharField(max_length=500, unique=True)),
                ('translation', models.CharField(max_length=10000)),
            ],
        ),
    ]
