# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20191030_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation0',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation1',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation2',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation3',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation4',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation5',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation6',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation7',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation8',
        ),
        migrations.RemoveField(
            model_name='translationmodel',
            name='translation9',
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='translation',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
