# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_auto_20191030_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationmodel',
            name='translation',
            field=models.CharField(max_length=10000),
        ),
    ]
