# Generated by Django 2.2.6 on 2019-11-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_passwordstring'),
        ('searchapp', '0006_auto_20191030_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('user_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.History')),
            ],
        ),
    ]
