# Generated by Django 2.2.3 on 2019-08-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='-', max_length=15),
        ),
    ]
