# Generated by Django 2.2.3 on 2019-08-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20190828_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
