# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191006_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': 'Password Code',
                'verbose_name_plural': 'Password Code',
                'ordering': ['-c_time'],
            },
        ),
    ]
